// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent.sql

package store

import (
	"context"
	"database/sql"
)

const cancelJobsRequested = `-- name: CancelJobsRequested :exec
UPDATE jobs SET status = 'cancelled', finished_at = unixepoch()
WHERE status IN ('queued','ready') AND cancel_requested = 1
`

func (q *Queries) CancelJobsRequested(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cancelJobsRequested)
	return err
}

const claimNextJob = `-- name: ClaimNextJob :one

UPDATE jobs
SET status = 'claimed', claimed_at = unixepoch(),
    lease_expires_at = unixepoch() + 60, attempt = attempt + 1
WHERE jobs.id = (
  SELECT j.id FROM jobs j
  WHERE j.server_id = ? AND j.status = 'ready'
  ORDER BY j.created_at, j.id LIMIT 1
)
RETURNING jobs.id, jobs.type, jobs.params_json, jobs.server_id, jobs.deploy_id
`

type ClaimNextJobRow struct {
	ID         int64         `json:"id"`
	Type       string        `json:"type"`
	ParamsJson string        `json:"params_json"`
	ServerID   int64         `json:"server_id"`
	DeployID   sql.NullInt64 `json:"deploy_id"`
}

// Job dispatch ---------------------------------------------------------------
func (q *Queries) ClaimNextJob(ctx context.Context, serverID int64) (ClaimNextJobRow, error) {
	row := q.db.QueryRowContext(ctx, claimNextJob, serverID)
	var i ClaimNextJobRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ParamsJson,
		&i.ServerID,
		&i.DeployID,
	)
	return i, err
}

const completeEnrollment = `-- name: CompleteEnrollment :exec
UPDATE servers
SET status = 'online', agent_token_hash = ?, agent_version = ?, hostname = ?,
    facts_json = ?, last_heartbeat_at = unixepoch(),
    enrollment_token_hash = NULL, enrollment_expires_at = NULL
WHERE id = ?
`

type CompleteEnrollmentParams struct {
	AgentTokenHash sql.NullString `json:"agent_token_hash"`
	AgentVersion   sql.NullString `json:"agent_version"`
	Hostname       string         `json:"hostname"`
	FactsJson      sql.NullString `json:"facts_json"`
	ID             int64          `json:"id"`
}

func (q *Queries) CompleteEnrollment(ctx context.Context, arg CompleteEnrollmentParams) error {
	_, err := q.db.ExecContext(ctx, completeEnrollment,
		arg.AgentTokenHash,
		arg.AgentVersion,
		arg.Hostname,
		arg.FactsJson,
		arg.ID,
	)
	return err
}

const countDeployJobsByStatus = `-- name: CountDeployJobsByStatus :one
SELECT
  COUNT(*) AS total,
  CAST(COALESCE(SUM(CASE WHEN status = 'succeeded' THEN 1 ELSE 0 END), 0) AS INTEGER) AS succeeded,
  CAST(COALESCE(SUM(CASE WHEN status IN ('failed','lost','cancelled') THEN 1 ELSE 0 END), 0) AS INTEGER) AS bad
FROM jobs WHERE deploy_id = ?
`

type CountDeployJobsByStatusRow struct {
	Total     int64 `json:"total"`
	Succeeded int64 `json:"succeeded"`
	Bad       int64 `json:"bad"`
}

func (q *Queries) CountDeployJobsByStatus(ctx context.Context, deployID sql.NullInt64) (CountDeployJobsByStatusRow, error) {
	row := q.db.QueryRowContext(ctx, countDeployJobsByStatus, deployID)
	var i CountDeployJobsByStatusRow
	err := row.Scan(&i.Total, &i.Succeeded, &i.Bad)
	return i, err
}

const createDeploy = `-- name: CreateDeploy :one

INSERT INTO deploys (kind, target_type, target_id, commit_sha, trigger, user_id)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, kind, target_type, target_id, commit_sha, "trigger", user_id, status, created_at, finished_at
`

type CreateDeployParams struct {
	Kind       string         `json:"kind"`
	TargetType string         `json:"target_type"`
	TargetID   int64          `json:"target_id"`
	CommitSha  sql.NullString `json:"commit_sha"`
	Trigger    string         `json:"trigger"`
	UserID     sql.NullInt64  `json:"user_id"`
}

// Deploys --------------------------------------------------------------------
func (q *Queries) CreateDeploy(ctx context.Context, arg CreateDeployParams) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, createDeploy,
		arg.Kind,
		arg.TargetType,
		arg.TargetID,
		arg.CommitSha,
		arg.Trigger,
		arg.UserID,
	)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.TargetType,
		&i.TargetID,
		&i.CommitSha,
		&i.Trigger,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (deploy_id, seq, server_id, type, params_json, lock_key, max_attempts)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, deploy_id, seq, server_id, type, params_json, lock_key, status, attempt, max_attempts, cancel_requested, lease_expires_at, claimed_at, started_at, finished_at, exit_code, error, result_json, created_at
`

type CreateJobParams struct {
	DeployID    sql.NullInt64  `json:"deploy_id"`
	Seq         int64          `json:"seq"`
	ServerID    int64          `json:"server_id"`
	Type        string         `json:"type"`
	ParamsJson  string         `json:"params_json"`
	LockKey     sql.NullString `json:"lock_key"`
	MaxAttempts int64          `json:"max_attempts"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.DeployID,
		arg.Seq,
		arg.ServerID,
		arg.Type,
		arg.ParamsJson,
		arg.LockKey,
		arg.MaxAttempts,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.DeployID,
		&i.Seq,
		&i.ServerID,
		&i.Type,
		&i.ParamsJson,
		&i.LockKey,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.CancelRequested,
		&i.LeaseExpiresAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExitCode,
		&i.Error,
		&i.ResultJson,
		&i.CreatedAt,
	)
	return i, err
}

const createServer = `-- name: CreateServer :one

INSERT INTO servers (name, hostname, status, enrollment_token_hash, enrollment_expires_at)
VALUES (?, ?, 'pending', ?, ?)
RETURNING id, name, hostname, status, enrollment_token_hash, enrollment_expires_at, agent_token_hash, agent_version, facts_json, last_heartbeat_at, created_at
`

type CreateServerParams struct {
	Name                string         `json:"name"`
	Hostname            string         `json:"hostname"`
	EnrollmentTokenHash sql.NullString `json:"enrollment_token_hash"`
	EnrollmentExpiresAt sql.NullInt64  `json:"enrollment_expires_at"`
}

// Server enrollment and heartbeat -------------------------------------------
func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRowContext(ctx, createServer,
		arg.Name,
		arg.Hostname,
		arg.EnrollmentTokenHash,
		arg.EnrollmentExpiresAt,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.Status,
		&i.EnrollmentTokenHash,
		&i.EnrollmentExpiresAt,
		&i.AgentTokenHash,
		&i.AgentVersion,
		&i.FactsJson,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
	)
	return i, err
}

const earlierSiblingsSucceeded = `-- name: EarlierSiblingsSucceeded :one
SELECT COUNT(*) AS not_done
FROM jobs
WHERE deploy_id = ? AND seq < ? AND status != 'succeeded'
`

type EarlierSiblingsSucceededParams struct {
	DeployID sql.NullInt64 `json:"deploy_id"`
	Seq      int64         `json:"seq"`
}

func (q *Queries) EarlierSiblingsSucceeded(ctx context.Context, arg EarlierSiblingsSucceededParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, earlierSiblingsSucceeded, arg.DeployID, arg.Seq)
	var not_done int64
	err := row.Scan(&not_done)
	return not_done, err
}

const expireLeases = `-- name: ExpireLeases :many

UPDATE jobs SET status = 'lost', finished_at = unixepoch()
WHERE status IN ('claimed','running') AND lease_expires_at < ?
RETURNING id, deploy_id, server_id
`

type ExpireLeasesRow struct {
	ID       int64         `json:"id"`
	DeployID sql.NullInt64 `json:"deploy_id"`
	ServerID int64         `json:"server_id"`
}

// Worker passes --------------------------------------------------------------
func (q *Queries) ExpireLeases(ctx context.Context, leaseExpiresAt sql.NullInt64) ([]ExpireLeasesRow, error) {
	rows, err := q.db.QueryContext(ctx, expireLeases, leaseExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpireLeasesRow{}
	for rows.Next() {
		var i ExpireLeasesRow
		if err := rows.Scan(&i.ID, &i.DeployID, &i.ServerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findServerByAgentTokenHash = `-- name: FindServerByAgentTokenHash :one
SELECT id, name, hostname, status, enrollment_token_hash, enrollment_expires_at, agent_token_hash, agent_version, facts_json, last_heartbeat_at, created_at FROM servers WHERE agent_token_hash = ? LIMIT 1
`

func (q *Queries) FindServerByAgentTokenHash(ctx context.Context, agentTokenHash sql.NullString) (Server, error) {
	row := q.db.QueryRowContext(ctx, findServerByAgentTokenHash, agentTokenHash)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.Status,
		&i.EnrollmentTokenHash,
		&i.EnrollmentExpiresAt,
		&i.AgentTokenHash,
		&i.AgentVersion,
		&i.FactsJson,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
	)
	return i, err
}

const findServerByEnrollmentHash = `-- name: FindServerByEnrollmentHash :one
SELECT id, name, hostname, status, enrollment_token_hash, enrollment_expires_at, agent_token_hash, agent_version, facts_json, last_heartbeat_at, created_at FROM servers
WHERE enrollment_token_hash = ? AND enrollment_expires_at > ?
LIMIT 1
`

type FindServerByEnrollmentHashParams struct {
	EnrollmentTokenHash sql.NullString `json:"enrollment_token_hash"`
	EnrollmentExpiresAt sql.NullInt64  `json:"enrollment_expires_at"`
}

func (q *Queries) FindServerByEnrollmentHash(ctx context.Context, arg FindServerByEnrollmentHashParams) (Server, error) {
	row := q.db.QueryRowContext(ctx, findServerByEnrollmentHash, arg.EnrollmentTokenHash, arg.EnrollmentExpiresAt)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.Status,
		&i.EnrollmentTokenHash,
		&i.EnrollmentExpiresAt,
		&i.AgentTokenHash,
		&i.AgentVersion,
		&i.FactsJson,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
	)
	return i, err
}

const finishDeploy = `-- name: FinishDeploy :exec
UPDATE deploys SET status = ?, finished_at = unixepoch() WHERE id = ?
`

type FinishDeployParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) FinishDeploy(ctx context.Context, arg FinishDeployParams) error {
	_, err := q.db.ExecContext(ctx, finishDeploy, arg.Status, arg.ID)
	return err
}

const finishJob = `-- name: FinishJob :exec
UPDATE jobs
SET status = ?, exit_code = ?, error = ?, result_json = ?, finished_at = unixepoch()
WHERE id = ?
`

type FinishJobParams struct {
	Status     string         `json:"status"`
	ExitCode   sql.NullInt64  `json:"exit_code"`
	Error      sql.NullString `json:"error"`
	ResultJson sql.NullString `json:"result_json"`
	ID         int64          `json:"id"`
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.ExecContext(ctx, finishJob,
		arg.Status,
		arg.ExitCode,
		arg.Error,
		arg.ResultJson,
		arg.ID,
	)
	return err
}

const getDeploy = `-- name: GetDeploy :one
SELECT id, kind, target_type, target_id, commit_sha, "trigger", user_id, status, created_at, finished_at FROM deploys WHERE id = ? LIMIT 1
`

func (q *Queries) GetDeploy(ctx context.Context, id int64) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, getDeploy, id)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.TargetType,
		&i.TargetID,
		&i.CommitSha,
		&i.Trigger,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, deploy_id, seq, server_id, type, params_json, lock_key, status, attempt, max_attempts, cancel_requested, lease_expires_at, claimed_at, started_at, finished_at, exit_code, error, result_json, created_at FROM jobs WHERE id = ? LIMIT 1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.DeployID,
		&i.Seq,
		&i.ServerID,
		&i.Type,
		&i.ParamsJson,
		&i.LockKey,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.CancelRequested,
		&i.LeaseExpiresAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExitCode,
		&i.Error,
		&i.ResultJson,
		&i.CreatedAt,
	)
	return i, err
}

const getServerByID = `-- name: GetServerByID :one
SELECT id, name, hostname, status, enrollment_token_hash, enrollment_expires_at, agent_token_hash, agent_version, facts_json, last_heartbeat_at, created_at FROM servers WHERE id = ? LIMIT 1
`

func (q *Queries) GetServerByID(ctx context.Context, id int64) (Server, error) {
	row := q.db.QueryRowContext(ctx, getServerByID, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.Status,
		&i.EnrollmentTokenHash,
		&i.EnrollmentExpiresAt,
		&i.AgentTokenHash,
		&i.AgentVersion,
		&i.FactsJson,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
	)
	return i, err
}

const heartbeat = `-- name: Heartbeat :exec
UPDATE servers
SET status = 'online', agent_version = ?, facts_json = ?, last_heartbeat_at = unixepoch()
WHERE id = ?
`

type HeartbeatParams struct {
	AgentVersion sql.NullString `json:"agent_version"`
	FactsJson    sql.NullString `json:"facts_json"`
	ID           int64          `json:"id"`
}

func (q *Queries) Heartbeat(ctx context.Context, arg HeartbeatParams) error {
	_, err := q.db.ExecContext(ctx, heartbeat, arg.AgentVersion, arg.FactsJson, arg.ID)
	return err
}

const insertJobLog = `-- name: InsertJobLog :exec
INSERT INTO job_logs (job_id, seq, ts, stream, line)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (job_id, seq) DO NOTHING
`

type InsertJobLogParams struct {
	JobID  int64  `json:"job_id"`
	Seq    int64  `json:"seq"`
	Ts     int64  `json:"ts"`
	Stream string `json:"stream"`
	Line   string `json:"line"`
}

func (q *Queries) InsertJobLog(ctx context.Context, arg InsertJobLogParams) error {
	_, err := q.db.ExecContext(ctx, insertJobLog,
		arg.JobID,
		arg.Seq,
		arg.Ts,
		arg.Stream,
		arg.Line,
	)
	return err
}

const latestResultForType = `-- name: LatestResultForType :one
SELECT result_json FROM jobs
WHERE server_id = ? AND type = ? AND status = 'succeeded'
ORDER BY finished_at DESC, id DESC
LIMIT 1
`

type LatestResultForTypeParams struct {
	ServerID int64  `json:"server_id"`
	Type     string `json:"type"`
}

func (q *Queries) LatestResultForType(ctx context.Context, arg LatestResultForTypeParams) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, latestResultForType, arg.ServerID, arg.Type)
	var result_json sql.NullString
	err := row.Scan(&result_json)
	return result_json, err
}

const listCancelRequestedForServer = `-- name: ListCancelRequestedForServer :many
SELECT id FROM jobs
WHERE server_id = ? AND cancel_requested = 1 AND status IN ('claimed','running')
`

func (q *Queries) ListCancelRequestedForServer(ctx context.Context, serverID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listCancelRequestedForServer, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobLogs = `-- name: ListJobLogs :many
SELECT job_id, seq, ts, stream, line FROM job_logs
WHERE job_id = ? AND seq > ?
ORDER BY seq
`

type ListJobLogsParams struct {
	JobID int64 `json:"job_id"`
	Seq   int64 `json:"seq"`
}

func (q *Queries) ListJobLogs(ctx context.Context, arg ListJobLogsParams) ([]JobLog, error) {
	rows, err := q.db.QueryContext(ctx, listJobLogs, arg.JobID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobLog{}
	for rows.Next() {
		var i JobLog
		if err := rows.Scan(
			&i.JobID,
			&i.Seq,
			&i.Ts,
			&i.Stream,
			&i.Line,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsForDeploy = `-- name: ListJobsForDeploy :many
SELECT id, deploy_id, seq, server_id, type, params_json, lock_key, status, attempt, max_attempts, cancel_requested, lease_expires_at, claimed_at, started_at, finished_at, exit_code, error, result_json, created_at FROM jobs WHERE deploy_id = ? ORDER BY seq, id
`

func (q *Queries) ListJobsForDeploy(ctx context.Context, deployID sql.NullInt64) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsForDeploy, deployID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.DeployID,
			&i.Seq,
			&i.ServerID,
			&i.Type,
			&i.ParamsJson,
			&i.LockKey,
			&i.Status,
			&i.Attempt,
			&i.MaxAttempts,
			&i.CancelRequested,
			&i.LeaseExpiresAt,
			&i.ClaimedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ExitCode,
			&i.Error,
			&i.ResultJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDeploys = `-- name: ListRecentDeploys :many
SELECT
  d.id, d.kind, d.target_type, d.target_id, d.commit_sha, d."trigger", d.user_id, d.status, d.created_at, d.finished_at,
  (SELECT j.id FROM jobs j WHERE j.deploy_id = d.id ORDER BY j.seq DESC LIMIT 1) AS last_job_id,
  (SELECT j.error FROM jobs j WHERE j.deploy_id = d.id AND j.error IS NOT NULL ORDER BY j.seq DESC LIMIT 1) AS last_error
FROM deploys d
ORDER BY d.created_at DESC LIMIT ?
`

type ListRecentDeploysRow struct {
	ID         int64          `json:"id"`
	Kind       string         `json:"kind"`
	TargetType string         `json:"target_type"`
	TargetID   int64          `json:"target_id"`
	CommitSha  sql.NullString `json:"commit_sha"`
	Trigger    string         `json:"trigger"`
	UserID     sql.NullInt64  `json:"user_id"`
	Status     string         `json:"status"`
	CreatedAt  int64          `json:"created_at"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
	LastJobID  int64          `json:"last_job_id"`
	LastError  sql.NullString `json:"last_error"`
}

func (q *Queries) ListRecentDeploys(ctx context.Context, limit int64) ([]ListRecentDeploysRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentDeploys, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentDeploysRow{}
	for rows.Next() {
		var i ListRecentDeploysRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.TargetType,
			&i.TargetID,
			&i.CommitSha,
			&i.Trigger,
			&i.UserID,
			&i.Status,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.LastJobID,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockHeld = `-- name: LockHeld :one
SELECT COUNT(*) AS held
FROM jobs
WHERE lock_key = ? AND status IN ('ready','claimed','running')
`

func (q *Queries) LockHeld(ctx context.Context, lockKey sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, lockHeld, lockKey)
	var held int64
	err := row.Scan(&held)
	return held, err
}

const markServersOffline = `-- name: MarkServersOffline :exec
UPDATE servers
SET status = 'offline'
WHERE status = 'online' AND last_heartbeat_at < ?
`

func (q *Queries) MarkServersOffline(ctx context.Context, lastHeartbeatAt sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, markServersOffline, lastHeartbeatAt)
	return err
}

const promoteJob = `-- name: PromoteJob :exec
UPDATE jobs SET status = 'ready' WHERE id = ? AND status = 'queued'
`

func (q *Queries) PromoteJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, promoteJob, id)
	return err
}

const readyJobsToPromote = `-- name: ReadyJobsToPromote :many
SELECT j.id, j.server_id, j.lock_key, j.deploy_id, j.seq
FROM jobs j
WHERE j.status = 'queued'
ORDER BY j.deploy_id, j.seq, j.id
`

type ReadyJobsToPromoteRow struct {
	ID       int64          `json:"id"`
	ServerID int64          `json:"server_id"`
	LockKey  sql.NullString `json:"lock_key"`
	DeployID sql.NullInt64  `json:"deploy_id"`
	Seq      int64          `json:"seq"`
}

// Candidate queued jobs with no earlier unfinished sibling and a free lock.
func (q *Queries) ReadyJobsToPromote(ctx context.Context) ([]ReadyJobsToPromoteRow, error) {
	rows, err := q.db.QueryContext(ctx, readyJobsToPromote)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadyJobsToPromoteRow{}
	for rows.Next() {
		var i ReadyJobsToPromoteRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.LockKey,
			&i.DeployID,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewLease = `-- name: RenewLease :exec
UPDATE jobs SET lease_expires_at = unixepoch() + 60
WHERE id = ? AND status IN ('claimed','running')
`

func (q *Queries) RenewLease(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, renewLease, id)
	return err
}

const setDeployRunning = `-- name: SetDeployRunning :exec
UPDATE deploys SET status = 'running' WHERE id = ? AND status = 'queued'
`

func (q *Queries) SetDeployRunning(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setDeployRunning, id)
	return err
}

const startJob = `-- name: StartJob :exec
UPDATE jobs SET status = 'running', started_at = unixepoch()
WHERE id = ? AND status = 'claimed'
`

func (q *Queries) StartJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, startJob, id)
	return err
}
