// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package store

import (
	"context"
	"database/sql"
)

const clearLoginAttempts = `-- name: ClearLoginAttempts :exec
DELETE FROM login_attempts WHERE key = ?
`

func (q *Queries) ClearLoginAttempts(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, clearLoginAttempts, key)
	return err
}

const countLoginAttempts = `-- name: CountLoginAttempts :one
SELECT COUNT(*) FROM login_attempts
WHERE key = ? AND ts > ?
`

type CountLoginAttemptsParams struct {
	Key string `json:"key"`
	Ts  int64  `json:"ts"`
}

func (q *Queries) CountLoginAttempts(ctx context.Context, arg CountLoginAttemptsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLoginAttempts, arg.Key, arg.Ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (user_id, actor, action, target_type, target_id, detail_json, ip)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditParams struct {
	UserID     sql.NullInt64  `json:"user_id"`
	Actor      string         `json:"actor"`
	Action     string         `json:"action"`
	TargetType sql.NullString `json:"target_type"`
	TargetID   sql.NullInt64  `json:"target_id"`
	DetailJson sql.NullString `json:"detail_json"`
	Ip         sql.NullString `json:"ip"`
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertAudit,
		arg.UserID,
		arg.Actor,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.DetailJson,
		arg.Ip,
	)
	return err
}

const insertLoginAttempt = `-- name: InsertLoginAttempt :exec
INSERT INTO login_attempts (key) VALUES (?)
`

func (q *Queries) InsertLoginAttempt(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, insertLoginAttempt, key)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT id, ts, user_id, actor, "action", target_type, target_id, detail_json, ip FROM audit_log
ORDER BY ts DESC
LIMIT ? OFFSET ?
`

type ListAuditParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAudit, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.UserID,
			&i.Actor,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.DetailJson,
			&i.Ip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeOldLoginAttempts = `-- name: PurgeOldLoginAttempts :exec
DELETE FROM login_attempts WHERE ts < ?
`

func (q *Queries) PurgeOldLoginAttempts(ctx context.Context, ts int64) error {
	_, err := q.db.ExecContext(ctx, purgeOldLoginAttempts, ts)
	return err
}
