// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package store

import (
	"context"
	"database/sql"
)

const countExpiringCerts = `-- name: CountExpiringCerts :one
SELECT
  (SELECT COUNT(*) FROM sites si WHERE si.ssl_enabled = 1 AND si.ssl_expires_at IS NOT NULL AND si.ssl_expires_at < ?)
  + (SELECT COUNT(*) FROM proxy_routes pr WHERE pr.ssl_enabled = 1 AND pr.ssl_expires_at IS NOT NULL AND pr.ssl_expires_at < ?) AS expiring
`

type CountExpiringCertsParams struct {
	SslExpiresAt   sql.NullInt64 `json:"ssl_expires_at"`
	SslExpiresAt_2 sql.NullInt64 `json:"ssl_expires_at_2"`
}

func (q *Queries) CountExpiringCerts(ctx context.Context, arg CountExpiringCertsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExpiringCerts, arg.SslExpiresAt, arg.SslExpiresAt_2)
	var expiring int64
	err := row.Scan(&expiring)
	return expiring, err
}

const countRunningJobs = `-- name: CountRunningJobs :one
SELECT COUNT(*) FROM jobs WHERE status IN ('claimed','running')
`

func (q *Queries) CountRunningJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunningJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countServers = `-- name: CountServers :one
SELECT COUNT(*) FROM servers
`

func (q *Queries) CountServers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countServers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countServersOffline = `-- name: CountServersOffline :one
SELECT COUNT(*) FROM servers WHERE status IN ('offline','disabled')
`

func (q *Queries) CountServersOffline(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countServersOffline)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countServersOnline = `-- name: CountServersOnline :one
SELECT COUNT(*) FROM servers WHERE status = 'online'
`

func (q *Queries) CountServersOnline(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countServersOnline)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSites = `-- name: CountSites :one
SELECT COUNT(*) FROM sites WHERE status != 'archived'
`

func (q *Queries) CountSites(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSites)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWebApps = `-- name: CountWebApps :one
SELECT COUNT(*) FROM web_apps
`

func (q *Queries) CountWebApps(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWebApps)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listServers = `-- name: ListServers :many
SELECT id, name, hostname, status, enrollment_token_hash, enrollment_expires_at, agent_token_hash, agent_version, facts_json, last_heartbeat_at, created_at FROM servers ORDER BY name
`

func (q *Queries) ListServers(ctx context.Context) ([]Server, error) {
	rows, err := q.db.QueryContext(ctx, listServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.Status,
			&i.EnrollmentTokenHash,
			&i.EnrollmentExpiresAt,
			&i.AgentTokenHash,
			&i.AgentVersion,
			&i.FactsJson,
			&i.LastHeartbeatAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
