// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type AppSource struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Repo       string `json:"repo"`
	Branch     string `json:"branch"`
	Kind       string `json:"kind"`
	AutoDeploy int64  `json:"auto_deploy"`
}

type AuditLog struct {
	ID         int64          `json:"id"`
	Ts         int64          `json:"ts"`
	UserID     sql.NullInt64  `json:"user_id"`
	Actor      string         `json:"actor"`
	Action     string         `json:"action"`
	TargetType sql.NullString `json:"target_type"`
	TargetID   sql.NullInt64  `json:"target_id"`
	DetailJson sql.NullString `json:"detail_json"`
	Ip         sql.NullString `json:"ip"`
}

type Bench struct {
	ID            int64          `json:"id"`
	ServerID      int64          `json:"server_id"`
	Name          string         `json:"name"`
	Path          string         `json:"path"`
	FrappeVersion sql.NullString `json:"frappe_version"`
	CreatedAt     int64          `json:"created_at"`
	FactsJson     string         `json:"facts_json"`
}

type Deploy struct {
	ID         int64          `json:"id"`
	Kind       string         `json:"kind"`
	TargetType string         `json:"target_type"`
	TargetID   int64          `json:"target_id"`
	CommitSha  sql.NullString `json:"commit_sha"`
	Trigger    string         `json:"trigger"`
	UserID     sql.NullInt64  `json:"user_id"`
	Status     string         `json:"status"`
	CreatedAt  int64          `json:"created_at"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
}

type FrappeApp struct {
	ID             int64          `json:"id"`
	BenchID        int64          `json:"bench_id"`
	AppSourceID    sql.NullInt64  `json:"app_source_id"`
	AppName        string         `json:"app_name"`
	CurrentCommit  sql.NullString `json:"current_commit"`
	PreviousCommit sql.NullString `json:"previous_commit"`
}

type FrappeDeployPoint struct {
	ID          int64  `json:"id"`
	BenchID     int64  `json:"bench_id"`
	AppName     string `json:"app_name"`
	PrevCommit  string `json:"prev_commit"`
	BackupsJson string `json:"backups_json"`
	CreatedAt   int64  `json:"created_at"`
}

type Job struct {
	ID              int64          `json:"id"`
	DeployID        sql.NullInt64  `json:"deploy_id"`
	Seq             int64          `json:"seq"`
	ServerID        int64          `json:"server_id"`
	Type            string         `json:"type"`
	ParamsJson      string         `json:"params_json"`
	LockKey         sql.NullString `json:"lock_key"`
	Status          string         `json:"status"`
	Attempt         int64          `json:"attempt"`
	MaxAttempts     int64          `json:"max_attempts"`
	CancelRequested int64          `json:"cancel_requested"`
	LeaseExpiresAt  sql.NullInt64  `json:"lease_expires_at"`
	ClaimedAt       sql.NullInt64  `json:"claimed_at"`
	StartedAt       sql.NullInt64  `json:"started_at"`
	FinishedAt      sql.NullInt64  `json:"finished_at"`
	ExitCode        sql.NullInt64  `json:"exit_code"`
	Error           sql.NullString `json:"error"`
	ResultJson      sql.NullString `json:"result_json"`
	CreatedAt       int64          `json:"created_at"`
}

type JobLog struct {
	JobID  int64  `json:"job_id"`
	Seq    int64  `json:"seq"`
	Ts     int64  `json:"ts"`
	Stream string `json:"stream"`
	Line   string `json:"line"`
}

type LoginAttempt struct {
	ID  int64  `json:"id"`
	Key string `json:"key"`
	Ts  int64  `json:"ts"`
}

type Pipeline struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	AppSourceID int64  `json:"app_source_id"`
	CreatedAt   int64  `json:"created_at"`
}

type PipelineEnv struct {
	ID              int64          `json:"id"`
	PipelineID      int64          `json:"pipeline_id"`
	Name            string         `json:"name"`
	Rank            int64          `json:"rank"`
	SiteID          int64          `json:"site_id"`
	RequireApproval int64          `json:"require_approval"`
	CurrentCommit   sql.NullString `json:"current_commit"`
	LastDeployID    sql.NullInt64  `json:"last_deploy_id"`
}

type ProxyRoute struct {
	ID           int64          `json:"id"`
	ServerID     int64          `json:"server_id"`
	Domain       string         `json:"domain"`
	Upstream     string         `json:"upstream"`
	WebAppID     sql.NullInt64  `json:"web_app_id"`
	SslEnabled   int64          `json:"ssl_enabled"`
	SslExpiresAt sql.NullInt64  `json:"ssl_expires_at"`
	ExtraSnippet sql.NullString `json:"extra_snippet"`
	ConfigHash   sql.NullString `json:"config_hash"`
	Status       string         `json:"status"`
}

type Secret struct {
	Name      string `json:"name"`
	ValueEnc  []byte `json:"value_enc"`
	UpdatedAt int64  `json:"updated_at"`
}

type Server struct {
	ID                  int64          `json:"id"`
	Name                string         `json:"name"`
	Hostname            string         `json:"hostname"`
	Status              string         `json:"status"`
	EnrollmentTokenHash sql.NullString `json:"enrollment_token_hash"`
	EnrollmentExpiresAt sql.NullInt64  `json:"enrollment_expires_at"`
	AgentTokenHash      sql.NullString `json:"agent_token_hash"`
	AgentVersion        sql.NullString `json:"agent_version"`
	FactsJson           sql.NullString `json:"facts_json"`
	LastHeartbeatAt     sql.NullInt64  `json:"last_heartbeat_at"`
	CreatedAt           int64          `json:"created_at"`
}

type Session struct {
	Token  string  `json:"token"`
	Data   []byte  `json:"data"`
	Expiry float64 `json:"expiry"`
}

type Site struct {
	ID           int64         `json:"id"`
	BenchID      int64         `json:"bench_id"`
	Domain       string        `json:"domain"`
	Status       string        `json:"status"`
	AppsJson     string        `json:"apps_json"`
	SslEnabled   int64         `json:"ssl_enabled"`
	SslExpiresAt sql.NullInt64 `json:"ssl_expires_at"`
	LastBackupAt sql.NullInt64 `json:"last_backup_at"`
	CreatedAt    int64         `json:"created_at"`
}

type User struct {
	ID            int64         `json:"id"`
	Email         string        `json:"email"`
	Name          string        `json:"name"`
	PasswordHash  string        `json:"password_hash"`
	TotpSecretEnc []byte        `json:"totp_secret_enc"`
	Role          string        `json:"role"`
	Disabled      int64         `json:"disabled"`
	CreatedAt     int64         `json:"created_at"`
	LastLoginAt   sql.NullInt64 `json:"last_login_at"`
}

type WebApp struct {
	ID             int64          `json:"id"`
	ServerID       int64          `json:"server_id"`
	AppSourceID    int64          `json:"app_source_id"`
	Name           string         `json:"name"`
	InternalPort   int64          `json:"internal_port"`
	ContainerPort  int64          `json:"container_port"`
	HealthPath     string         `json:"health_path"`
	EnvEnc         []byte         `json:"env_enc"`
	CurrentCommit  sql.NullString `json:"current_commit"`
	PreviousCommit sql.NullString `json:"previous_commit"`
	Status         string         `json:"status"`
}

type WebhookDelivery struct {
	DeliveryID string `json:"delivery_id"`
	Event      string `json:"event"`
	ReceivedAt int64  `json:"received_at"`
}
