// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipelines.sql

package store

import (
	"context"
	"database/sql"
)

const createPipeline = `-- name: CreatePipeline :one

INSERT INTO pipelines (name, app_source_id)
VALUES (?, ?)
RETURNING id, name, app_source_id, created_at
`

type CreatePipelineParams struct {
	Name        string `json:"name"`
	AppSourceID int64  `json:"app_source_id"`
}

// Pipelines (dev -> staging -> prod release trains) -------------------------
func (q *Queries) CreatePipeline(ctx context.Context, arg CreatePipelineParams) (Pipeline, error) {
	row := q.db.QueryRowContext(ctx, createPipeline, arg.Name, arg.AppSourceID)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AppSourceID,
		&i.CreatedAt,
	)
	return i, err
}

const createPipelineEnv = `-- name: CreatePipelineEnv :one
INSERT INTO pipeline_envs (pipeline_id, name, rank, site_id, require_approval)
VALUES (?, ?, ?, ?, ?)
RETURNING id, pipeline_id, name, rank, site_id, require_approval, current_commit, last_deploy_id
`

type CreatePipelineEnvParams struct {
	PipelineID      int64  `json:"pipeline_id"`
	Name            string `json:"name"`
	Rank            int64  `json:"rank"`
	SiteID          int64  `json:"site_id"`
	RequireApproval int64  `json:"require_approval"`
}

func (q *Queries) CreatePipelineEnv(ctx context.Context, arg CreatePipelineEnvParams) (PipelineEnv, error) {
	row := q.db.QueryRowContext(ctx, createPipelineEnv,
		arg.PipelineID,
		arg.Name,
		arg.Rank,
		arg.SiteID,
		arg.RequireApproval,
	)
	var i PipelineEnv
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Rank,
		&i.SiteID,
		&i.RequireApproval,
		&i.CurrentCommit,
		&i.LastDeployID,
	)
	return i, err
}

const deletePipeline = `-- name: DeletePipeline :exec
DELETE FROM pipelines WHERE id = ?
`

func (q *Queries) DeletePipeline(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePipeline, id)
	return err
}

const deletePipelineEnvs = `-- name: DeletePipelineEnvs :exec
DELETE FROM pipeline_envs WHERE pipeline_id = ?
`

func (q *Queries) DeletePipelineEnvs(ctx context.Context, pipelineID int64) error {
	_, err := q.db.ExecContext(ctx, deletePipelineEnvs, pipelineID)
	return err
}

const getPipeline = `-- name: GetPipeline :one
SELECT id, name, app_source_id, created_at FROM pipelines WHERE id = ? LIMIT 1
`

func (q *Queries) GetPipeline(ctx context.Context, id int64) (Pipeline, error) {
	row := q.db.QueryRowContext(ctx, getPipeline, id)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AppSourceID,
		&i.CreatedAt,
	)
	return i, err
}

const getPipelineEnvByDeploy = `-- name: GetPipelineEnvByDeploy :one
SELECT id, pipeline_id, name, rank, site_id, require_approval, current_commit, last_deploy_id FROM pipeline_envs WHERE last_deploy_id = ? LIMIT 1
`

func (q *Queries) GetPipelineEnvByDeploy(ctx context.Context, lastDeployID sql.NullInt64) (PipelineEnv, error) {
	row := q.db.QueryRowContext(ctx, getPipelineEnvByDeploy, lastDeployID)
	var i PipelineEnv
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Rank,
		&i.SiteID,
		&i.RequireApproval,
		&i.CurrentCommit,
		&i.LastDeployID,
	)
	return i, err
}

const getPipelineEnvByRank = `-- name: GetPipelineEnvByRank :one
SELECT id, pipeline_id, name, rank, site_id, require_approval, current_commit, last_deploy_id FROM pipeline_envs WHERE pipeline_id = ? AND rank = ? LIMIT 1
`

type GetPipelineEnvByRankParams struct {
	PipelineID int64 `json:"pipeline_id"`
	Rank       int64 `json:"rank"`
}

func (q *Queries) GetPipelineEnvByRank(ctx context.Context, arg GetPipelineEnvByRankParams) (PipelineEnv, error) {
	row := q.db.QueryRowContext(ctx, getPipelineEnvByRank, arg.PipelineID, arg.Rank)
	var i PipelineEnv
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Rank,
		&i.SiteID,
		&i.RequireApproval,
		&i.CurrentCommit,
		&i.LastDeployID,
	)
	return i, err
}

const listEnvsForPipeline = `-- name: ListEnvsForPipeline :many
SELECT
  pe.id, pe.pipeline_id, pe.name, pe.rank, pe.site_id,
  pe.require_approval, pe.current_commit, pe.last_deploy_id,
  s.domain       AS site_domain,
  s.status       AS site_status,
  b.id           AS bench_id,
  b.path         AS bench_path,
  srv.id         AS server_id,
  srv.name       AS server_name,
  srv.status     AS server_status,
  d.status       AS deploy_status
FROM pipeline_envs pe
JOIN sites   s   ON s.id = pe.site_id
JOIN benches b   ON b.id = s.bench_id
JOIN servers srv ON srv.id = b.server_id
LEFT JOIN deploys d ON d.id = pe.last_deploy_id
WHERE pe.pipeline_id = ?
ORDER BY pe.rank
`

type ListEnvsForPipelineRow struct {
	ID              int64          `json:"id"`
	PipelineID      int64          `json:"pipeline_id"`
	Name            string         `json:"name"`
	Rank            int64          `json:"rank"`
	SiteID          int64          `json:"site_id"`
	RequireApproval int64          `json:"require_approval"`
	CurrentCommit   sql.NullString `json:"current_commit"`
	LastDeployID    sql.NullInt64  `json:"last_deploy_id"`
	SiteDomain      string         `json:"site_domain"`
	SiteStatus      string         `json:"site_status"`
	BenchID         int64          `json:"bench_id"`
	BenchPath       string         `json:"bench_path"`
	ServerID        int64          `json:"server_id"`
	ServerName      string         `json:"server_name"`
	ServerStatus    string         `json:"server_status"`
	DeployStatus    sql.NullString `json:"deploy_status"`
}

// Envs joined to their site + bench + server so the API can show which agent
// each environment runs on, its domain, and its deploy status.
func (q *Queries) ListEnvsForPipeline(ctx context.Context, pipelineID int64) ([]ListEnvsForPipelineRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnvsForPipeline, pipelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvsForPipelineRow{}
	for rows.Next() {
		var i ListEnvsForPipelineRow
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.Name,
			&i.Rank,
			&i.SiteID,
			&i.RequireApproval,
			&i.CurrentCommit,
			&i.LastDeployID,
			&i.SiteDomain,
			&i.SiteStatus,
			&i.BenchID,
			&i.BenchPath,
			&i.ServerID,
			&i.ServerName,
			&i.ServerStatus,
			&i.DeployStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelines = `-- name: ListPipelines :many
SELECT id, name, app_source_id, created_at FROM pipelines ORDER BY name
`

func (q *Queries) ListPipelines(ctx context.Context) ([]Pipeline, error) {
	rows, err := q.db.QueryContext(ctx, listPipelines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pipeline{}
	for rows.Next() {
		var i Pipeline
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AppSourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEnvCommit = `-- name: SetEnvCommit :exec
UPDATE pipeline_envs SET current_commit = ? WHERE id = ?
`

type SetEnvCommitParams struct {
	CurrentCommit sql.NullString `json:"current_commit"`
	ID            int64          `json:"id"`
}

func (q *Queries) SetEnvCommit(ctx context.Context, arg SetEnvCommitParams) error {
	_, err := q.db.ExecContext(ctx, setEnvCommit, arg.CurrentCommit, arg.ID)
	return err
}

const setEnvDeploy = `-- name: SetEnvDeploy :exec
UPDATE pipeline_envs SET last_deploy_id = ? WHERE id = ?
`

type SetEnvDeployParams struct {
	LastDeployID sql.NullInt64 `json:"last_deploy_id"`
	ID           int64         `json:"id"`
}

func (q *Queries) SetEnvDeploy(ctx context.Context, arg SetEnvDeployParams) error {
	_, err := q.db.ExecContext(ctx, setEnvDeploy, arg.LastDeployID, arg.ID)
	return err
}
