// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	BenchesWithApp(ctx context.Context, appSourceID sql.NullInt64) ([]Bench, error)
	CancelJobsRequested(ctx context.Context) error
	// Job dispatch ---------------------------------------------------------------
	ClaimNextJob(ctx context.Context, serverID int64) (ClaimNextJobRow, error)
	ClearLoginAttempts(ctx context.Context, key string) error
	ClearUserTOTP(ctx context.Context, id int64) error
	CompleteEnrollment(ctx context.Context, arg CompleteEnrollmentParams) error
	CountDeployJobsByStatus(ctx context.Context, deployID sql.NullInt64) (CountDeployJobsByStatusRow, error)
	CountExpiringCerts(ctx context.Context, arg CountExpiringCertsParams) (int64, error)
	CountLoginAttempts(ctx context.Context, arg CountLoginAttemptsParams) (int64, error)
	CountRunningJobs(ctx context.Context) (int64, error)
	CountServers(ctx context.Context) (int64, error)
	CountServersOffline(ctx context.Context) (int64, error)
	CountServersOnline(ctx context.Context) (int64, error)
	CountSites(ctx context.Context) (int64, error)
	CountWebApps(ctx context.Context) (int64, error)
	// App sources ----------------------------------------------------------------
	CreateAppSource(ctx context.Context, arg CreateAppSourceParams) (AppSource, error)
	// Benches / frappe apps / sites ----------------------------------------------
	CreateBench(ctx context.Context, arg CreateBenchParams) (Bench, error)
	// Deploys --------------------------------------------------------------------
	CreateDeploy(ctx context.Context, arg CreateDeployParams) (Deploy, error)
	CreateFrappeApp(ctx context.Context, arg CreateFrappeAppParams) (FrappeApp, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	// Proxy routes ---------------------------------------------------------------
	CreateProxyRoute(ctx context.Context, arg CreateProxyRouteParams) (ProxyRoute, error)
	// Server enrollment and heartbeat -------------------------------------------
	CreateServer(ctx context.Context, arg CreateServerParams) (Server, error)
	CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Web apps -------------------------------------------------------------------
	CreateWebApp(ctx context.Context, arg CreateWebAppParams) (WebApp, error)
	DeleteSecret(ctx context.Context, name string) error
	EarlierSiblingsSucceeded(ctx context.Context, arg EarlierSiblingsSucceededParams) (int64, error)
	// Worker passes --------------------------------------------------------------
	ExpireLeases(ctx context.Context, leaseExpiresAt sql.NullInt64) ([]ExpireLeasesRow, error)
	FindAppSourcesByRepoBranch(ctx context.Context, arg FindAppSourcesByRepoBranchParams) ([]AppSource, error)
	FindServerByAgentTokenHash(ctx context.Context, agentTokenHash sql.NullString) (Server, error)
	FindServerByEnrollmentHash(ctx context.Context, arg FindServerByEnrollmentHashParams) (Server, error)
	FinishDeploy(ctx context.Context, arg FinishDeployParams) error
	FinishJob(ctx context.Context, arg FinishJobParams) error
	GetAppSource(ctx context.Context, id int64) (AppSource, error)
	GetBench(ctx context.Context, id int64) (Bench, error)
	GetDeploy(ctx context.Context, id int64) (Deploy, error)
	GetJob(ctx context.Context, id int64) (Job, error)
	GetProxyRoute(ctx context.Context, id int64) (ProxyRoute, error)
	GetSecret(ctx context.Context, name string) ([]byte, error)
	GetServerByID(ctx context.Context, id int64) (Server, error)
	GetSite(ctx context.Context, id int64) (Site, error)
	GetSiteByDomain(ctx context.Context, domain string) (Site, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetWebApp(ctx context.Context, id int64) (WebApp, error)
	GetWebAppByName(ctx context.Context, name string) (WebApp, error)
	GetWebhookDelivery(ctx context.Context, deliveryID string) (string, error)
	Heartbeat(ctx context.Context, arg HeartbeatParams) error
	InsertAudit(ctx context.Context, arg InsertAuditParams) error
	InsertJobLog(ctx context.Context, arg InsertJobLogParams) error
	InsertLoginAttempt(ctx context.Context, key string) error
	LatestResultForType(ctx context.Context, arg LatestResultForTypeParams) (sql.NullString, error)
	ListAppSources(ctx context.Context) ([]AppSource, error)
	ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditLog, error)
	ListBenches(ctx context.Context) ([]Bench, error)
	ListBenchesForServer(ctx context.Context, serverID int64) ([]Bench, error)
	ListCancelRequestedForServer(ctx context.Context, serverID int64) ([]int64, error)
	ListFrappeAppsForBench(ctx context.Context, benchID int64) ([]FrappeApp, error)
	ListJobLogs(ctx context.Context, arg ListJobLogsParams) ([]JobLog, error)
	ListJobsForDeploy(ctx context.Context, deployID sql.NullInt64) ([]Job, error)
	ListProxyRoutes(ctx context.Context) ([]ProxyRoute, error)
	ListProxyRoutesForServer(ctx context.Context, serverID int64) ([]ProxyRoute, error)
	ListRecentDeploys(ctx context.Context, limit int64) ([]Deploy, error)
	ListServers(ctx context.Context) ([]Server, error)
	ListSites(ctx context.Context) ([]Site, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListWebApps(ctx context.Context) ([]WebApp, error)
	LockHeld(ctx context.Context, lockKey sql.NullString) (int64, error)
	MarkServersOffline(ctx context.Context, lastHeartbeatAt sql.NullInt64) error
	PromoteJob(ctx context.Context, id int64) error
	PurgeOldLoginAttempts(ctx context.Context, ts int64) error
	PurgeOldWebhookDeliveries(ctx context.Context, receivedAt int64) error
	PutSecret(ctx context.Context, arg PutSecretParams) error
	// Candidate queued jobs with no earlier unfinished sibling and a free lock.
	ReadyJobsToPromote(ctx context.Context) ([]ReadyJobsToPromoteRow, error)
	RecordWebhookDelivery(ctx context.Context, arg RecordWebhookDeliveryParams) error
	RenewLease(ctx context.Context, id int64) error
	RouteOrSiteExistsForDomain(ctx context.Context, arg RouteOrSiteExistsForDomainParams) (int64, error)
	SetAppSourceAutoDeploy(ctx context.Context, arg SetAppSourceAutoDeployParams) error
	SetDeployRunning(ctx context.Context, id int64) error
	SetFrappeAppCommit(ctx context.Context, arg SetFrappeAppCommitParams) error
	SetProxyRouteApplied(ctx context.Context, arg SetProxyRouteAppliedParams) error
	SetProxyRouteStatus(ctx context.Context, arg SetProxyRouteStatusParams) error
	SetSiteSSL(ctx context.Context, arg SetSiteSSLParams) error
	SetSiteStatus(ctx context.Context, arg SetSiteStatusParams) error
	SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	SetUserTOTP(ctx context.Context, arg SetUserTOTPParams) error
	SetWebAppCommit(ctx context.Context, arg SetWebAppCommitParams) error
	SetWebAppStatus(ctx context.Context, arg SetWebAppStatusParams) error
	SitesForBench(ctx context.Context, benchID int64) ([]Site, error)
	StartJob(ctx context.Context, id int64) error
	TouchUserLogin(ctx context.Context, id int64) error
	WebAppsForSource(ctx context.Context, appSourceID int64) ([]WebApp, error)
}

var _ Querier = (*Queries)(nil)
