// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package store

import (
	"context"
	"database/sql"
)

const archiveSite = `-- name: ArchiveSite :exec
UPDATE sites SET status = 'archived' WHERE id = ?
`

func (q *Queries) ArchiveSite(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, archiveSite, id)
	return err
}

const benchesWithApp = `-- name: BenchesWithApp :many
SELECT b.id, b.server_id, b.name, b.path, b.frappe_version, b.created_at, b.facts_json FROM benches b
JOIN frappe_apps fa ON fa.bench_id = b.id
WHERE fa.app_source_id = ?
`

func (q *Queries) BenchesWithApp(ctx context.Context, appSourceID sql.NullInt64) ([]Bench, error) {
	rows, err := q.db.QueryContext(ctx, benchesWithApp, appSourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bench{}
	for rows.Next() {
		var i Bench
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Name,
			&i.Path,
			&i.FrappeVersion,
			&i.CreatedAt,
			&i.FactsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAppSource = `-- name: CreateAppSource :one

INSERT INTO app_sources (name, repo, branch, kind, auto_deploy)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, repo, branch, kind, auto_deploy
`

type CreateAppSourceParams struct {
	Name       string `json:"name"`
	Repo       string `json:"repo"`
	Branch     string `json:"branch"`
	Kind       string `json:"kind"`
	AutoDeploy int64  `json:"auto_deploy"`
}

// App sources ----------------------------------------------------------------
func (q *Queries) CreateAppSource(ctx context.Context, arg CreateAppSourceParams) (AppSource, error) {
	row := q.db.QueryRowContext(ctx, createAppSource,
		arg.Name,
		arg.Repo,
		arg.Branch,
		arg.Kind,
		arg.AutoDeploy,
	)
	var i AppSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Repo,
		&i.Branch,
		&i.Kind,
		&i.AutoDeploy,
	)
	return i, err
}

const createBench = `-- name: CreateBench :one

INSERT INTO benches (server_id, name, path, frappe_version)
VALUES (?, ?, ?, ?)
RETURNING id, server_id, name, path, frappe_version, created_at, facts_json
`

type CreateBenchParams struct {
	ServerID      int64          `json:"server_id"`
	Name          string         `json:"name"`
	Path          string         `json:"path"`
	FrappeVersion sql.NullString `json:"frappe_version"`
}

// Benches / frappe apps / sites ----------------------------------------------
func (q *Queries) CreateBench(ctx context.Context, arg CreateBenchParams) (Bench, error) {
	row := q.db.QueryRowContext(ctx, createBench,
		arg.ServerID,
		arg.Name,
		arg.Path,
		arg.FrappeVersion,
	)
	var i Bench
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.Path,
		&i.FrappeVersion,
		&i.CreatedAt,
		&i.FactsJson,
	)
	return i, err
}

const createFrappeApp = `-- name: CreateFrappeApp :one
INSERT INTO frappe_apps (bench_id, app_source_id, app_name, current_commit)
VALUES (?, ?, ?, ?)
RETURNING id, bench_id, app_source_id, app_name, current_commit, previous_commit
`

type CreateFrappeAppParams struct {
	BenchID       int64          `json:"bench_id"`
	AppSourceID   sql.NullInt64  `json:"app_source_id"`
	AppName       string         `json:"app_name"`
	CurrentCommit sql.NullString `json:"current_commit"`
}

func (q *Queries) CreateFrappeApp(ctx context.Context, arg CreateFrappeAppParams) (FrappeApp, error) {
	row := q.db.QueryRowContext(ctx, createFrappeApp,
		arg.BenchID,
		arg.AppSourceID,
		arg.AppName,
		arg.CurrentCommit,
	)
	var i FrappeApp
	err := row.Scan(
		&i.ID,
		&i.BenchID,
		&i.AppSourceID,
		&i.AppName,
		&i.CurrentCommit,
		&i.PreviousCommit,
	)
	return i, err
}

const createProxyRoute = `-- name: CreateProxyRoute :one

INSERT INTO proxy_routes (server_id, domain, upstream, web_app_id, ssl_enabled, extra_snippet, status)
VALUES (?, ?, ?, ?, ?, ?, 'pending')
RETURNING id, server_id, domain, upstream, web_app_id, ssl_enabled, ssl_expires_at, extra_snippet, config_hash, status
`

type CreateProxyRouteParams struct {
	ServerID     int64          `json:"server_id"`
	Domain       string         `json:"domain"`
	Upstream     string         `json:"upstream"`
	WebAppID     sql.NullInt64  `json:"web_app_id"`
	SslEnabled   int64          `json:"ssl_enabled"`
	ExtraSnippet sql.NullString `json:"extra_snippet"`
}

// Proxy routes ---------------------------------------------------------------
func (q *Queries) CreateProxyRoute(ctx context.Context, arg CreateProxyRouteParams) (ProxyRoute, error) {
	row := q.db.QueryRowContext(ctx, createProxyRoute,
		arg.ServerID,
		arg.Domain,
		arg.Upstream,
		arg.WebAppID,
		arg.SslEnabled,
		arg.ExtraSnippet,
	)
	var i ProxyRoute
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Domain,
		&i.Upstream,
		&i.WebAppID,
		&i.SslEnabled,
		&i.SslExpiresAt,
		&i.ExtraSnippet,
		&i.ConfigHash,
		&i.Status,
	)
	return i, err
}

const createSite = `-- name: CreateSite :one
INSERT INTO sites (bench_id, domain, status, apps_json, ssl_enabled)
VALUES (?, ?, ?, ?, ?)
RETURNING id, bench_id, domain, status, apps_json, ssl_enabled, ssl_expires_at, last_backup_at, created_at
`

type CreateSiteParams struct {
	BenchID    int64  `json:"bench_id"`
	Domain     string `json:"domain"`
	Status     string `json:"status"`
	AppsJson   string `json:"apps_json"`
	SslEnabled int64  `json:"ssl_enabled"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRowContext(ctx, createSite,
		arg.BenchID,
		arg.Domain,
		arg.Status,
		arg.AppsJson,
		arg.SslEnabled,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.BenchID,
		&i.Domain,
		&i.Status,
		&i.AppsJson,
		&i.SslEnabled,
		&i.SslExpiresAt,
		&i.LastBackupAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWebApp = `-- name: CreateWebApp :one

INSERT INTO web_apps (server_id, app_source_id, name, internal_port, container_port, health_path, env_enc, status)
VALUES (?, ?, ?, ?, ?, ?, ?, 'new')
RETURNING id, server_id, app_source_id, name, internal_port, container_port, health_path, env_enc, current_commit, previous_commit, status
`

type CreateWebAppParams struct {
	ServerID      int64  `json:"server_id"`
	AppSourceID   int64  `json:"app_source_id"`
	Name          string `json:"name"`
	InternalPort  int64  `json:"internal_port"`
	ContainerPort int64  `json:"container_port"`
	HealthPath    string `json:"health_path"`
	EnvEnc        []byte `json:"env_enc"`
}

// Web apps -------------------------------------------------------------------
func (q *Queries) CreateWebApp(ctx context.Context, arg CreateWebAppParams) (WebApp, error) {
	row := q.db.QueryRowContext(ctx, createWebApp,
		arg.ServerID,
		arg.AppSourceID,
		arg.Name,
		arg.InternalPort,
		arg.ContainerPort,
		arg.HealthPath,
		arg.EnvEnc,
	)
	var i WebApp
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.AppSourceID,
		&i.Name,
		&i.InternalPort,
		&i.ContainerPort,
		&i.HealthPath,
		&i.EnvEnc,
		&i.CurrentCommit,
		&i.PreviousCommit,
		&i.Status,
	)
	return i, err
}

const deleteSiteRow = `-- name: DeleteSiteRow :exec
DELETE FROM sites WHERE id = ?
`

func (q *Queries) DeleteSiteRow(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSiteRow, id)
	return err
}

const findAppSourcesByRepoBranch = `-- name: FindAppSourcesByRepoBranch :many
SELECT id, name, repo, branch, kind, auto_deploy FROM app_sources WHERE repo = ? AND branch = ? AND auto_deploy = 1
`

type FindAppSourcesByRepoBranchParams struct {
	Repo   string `json:"repo"`
	Branch string `json:"branch"`
}

func (q *Queries) FindAppSourcesByRepoBranch(ctx context.Context, arg FindAppSourcesByRepoBranchParams) ([]AppSource, error) {
	rows, err := q.db.QueryContext(ctx, findAppSourcesByRepoBranch, arg.Repo, arg.Branch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSource{}
	for rows.Next() {
		var i AppSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Repo,
			&i.Branch,
			&i.Kind,
			&i.AutoDeploy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppSource = `-- name: GetAppSource :one
SELECT id, name, repo, branch, kind, auto_deploy FROM app_sources WHERE id = ? LIMIT 1
`

func (q *Queries) GetAppSource(ctx context.Context, id int64) (AppSource, error) {
	row := q.db.QueryRowContext(ctx, getAppSource, id)
	var i AppSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Repo,
		&i.Branch,
		&i.Kind,
		&i.AutoDeploy,
	)
	return i, err
}

const getAppSourceByName = `-- name: GetAppSourceByName :one
SELECT id, name, repo, branch, kind, auto_deploy FROM app_sources WHERE name = ? LIMIT 1
`

func (q *Queries) GetAppSourceByName(ctx context.Context, name string) (AppSource, error) {
	row := q.db.QueryRowContext(ctx, getAppSourceByName, name)
	var i AppSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Repo,
		&i.Branch,
		&i.Kind,
		&i.AutoDeploy,
	)
	return i, err
}

const getBench = `-- name: GetBench :one
SELECT id, server_id, name, path, frappe_version, created_at, facts_json FROM benches WHERE id = ? LIMIT 1
`

func (q *Queries) GetBench(ctx context.Context, id int64) (Bench, error) {
	row := q.db.QueryRowContext(ctx, getBench, id)
	var i Bench
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.Path,
		&i.FrappeVersion,
		&i.CreatedAt,
		&i.FactsJson,
	)
	return i, err
}

const getDeployPoint = `-- name: GetDeployPoint :one
SELECT id, bench_id, app_name, prev_commit, backups_json, created_at FROM frappe_deploy_points WHERE bench_id = ? AND app_name = ? LIMIT 1
`

type GetDeployPointParams struct {
	BenchID int64  `json:"bench_id"`
	AppName string `json:"app_name"`
}

func (q *Queries) GetDeployPoint(ctx context.Context, arg GetDeployPointParams) (FrappeDeployPoint, error) {
	row := q.db.QueryRowContext(ctx, getDeployPoint, arg.BenchID, arg.AppName)
	var i FrappeDeployPoint
	err := row.Scan(
		&i.ID,
		&i.BenchID,
		&i.AppName,
		&i.PrevCommit,
		&i.BackupsJson,
		&i.CreatedAt,
	)
	return i, err
}

const getProxyRoute = `-- name: GetProxyRoute :one
SELECT id, server_id, domain, upstream, web_app_id, ssl_enabled, ssl_expires_at, extra_snippet, config_hash, status FROM proxy_routes WHERE id = ? LIMIT 1
`

func (q *Queries) GetProxyRoute(ctx context.Context, id int64) (ProxyRoute, error) {
	row := q.db.QueryRowContext(ctx, getProxyRoute, id)
	var i ProxyRoute
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Domain,
		&i.Upstream,
		&i.WebAppID,
		&i.SslEnabled,
		&i.SslExpiresAt,
		&i.ExtraSnippet,
		&i.ConfigHash,
		&i.Status,
	)
	return i, err
}

const getSite = `-- name: GetSite :one
SELECT id, bench_id, domain, status, apps_json, ssl_enabled, ssl_expires_at, last_backup_at, created_at FROM sites WHERE id = ? LIMIT 1
`

func (q *Queries) GetSite(ctx context.Context, id int64) (Site, error) {
	row := q.db.QueryRowContext(ctx, getSite, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.BenchID,
		&i.Domain,
		&i.Status,
		&i.AppsJson,
		&i.SslEnabled,
		&i.SslExpiresAt,
		&i.LastBackupAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteByDomain = `-- name: GetSiteByDomain :one
SELECT id, bench_id, domain, status, apps_json, ssl_enabled, ssl_expires_at, last_backup_at, created_at FROM sites WHERE domain = ? LIMIT 1
`

func (q *Queries) GetSiteByDomain(ctx context.Context, domain string) (Site, error) {
	row := q.db.QueryRowContext(ctx, getSiteByDomain, domain)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.BenchID,
		&i.Domain,
		&i.Status,
		&i.AppsJson,
		&i.SslEnabled,
		&i.SslExpiresAt,
		&i.LastBackupAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWebApp = `-- name: GetWebApp :one
SELECT id, server_id, app_source_id, name, internal_port, container_port, health_path, env_enc, current_commit, previous_commit, status FROM web_apps WHERE id = ? LIMIT 1
`

func (q *Queries) GetWebApp(ctx context.Context, id int64) (WebApp, error) {
	row := q.db.QueryRowContext(ctx, getWebApp, id)
	var i WebApp
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.AppSourceID,
		&i.Name,
		&i.InternalPort,
		&i.ContainerPort,
		&i.HealthPath,
		&i.EnvEnc,
		&i.CurrentCommit,
		&i.PreviousCommit,
		&i.Status,
	)
	return i, err
}

const getWebAppByName = `-- name: GetWebAppByName :one
SELECT id, server_id, app_source_id, name, internal_port, container_port, health_path, env_enc, current_commit, previous_commit, status FROM web_apps WHERE name = ? LIMIT 1
`

func (q *Queries) GetWebAppByName(ctx context.Context, name string) (WebApp, error) {
	row := q.db.QueryRowContext(ctx, getWebAppByName, name)
	var i WebApp
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.AppSourceID,
		&i.Name,
		&i.InternalPort,
		&i.ContainerPort,
		&i.HealthPath,
		&i.EnvEnc,
		&i.CurrentCommit,
		&i.PreviousCommit,
		&i.Status,
	)
	return i, err
}

const listAppSources = `-- name: ListAppSources :many
SELECT id, name, repo, branch, kind, auto_deploy FROM app_sources ORDER BY name
`

func (q *Queries) ListAppSources(ctx context.Context) ([]AppSource, error) {
	rows, err := q.db.QueryContext(ctx, listAppSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSource{}
	for rows.Next() {
		var i AppSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Repo,
			&i.Branch,
			&i.Kind,
			&i.AutoDeploy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBenches = `-- name: ListBenches :many
SELECT id, server_id, name, path, frappe_version, created_at, facts_json FROM benches ORDER BY server_id, path
`

func (q *Queries) ListBenches(ctx context.Context) ([]Bench, error) {
	rows, err := q.db.QueryContext(ctx, listBenches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bench{}
	for rows.Next() {
		var i Bench
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Name,
			&i.Path,
			&i.FrappeVersion,
			&i.CreatedAt,
			&i.FactsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBenchesForServer = `-- name: ListBenchesForServer :many
SELECT id, server_id, name, path, frappe_version, created_at, facts_json FROM benches WHERE server_id = ? ORDER BY path
`

func (q *Queries) ListBenchesForServer(ctx context.Context, serverID int64) ([]Bench, error) {
	rows, err := q.db.QueryContext(ctx, listBenchesForServer, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bench{}
	for rows.Next() {
		var i Bench
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Name,
			&i.Path,
			&i.FrappeVersion,
			&i.CreatedAt,
			&i.FactsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFrappeAppsForBench = `-- name: ListFrappeAppsForBench :many
SELECT id, bench_id, app_source_id, app_name, current_commit, previous_commit FROM frappe_apps WHERE bench_id = ? ORDER BY app_name
`

func (q *Queries) ListFrappeAppsForBench(ctx context.Context, benchID int64) ([]FrappeApp, error) {
	rows, err := q.db.QueryContext(ctx, listFrappeAppsForBench, benchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FrappeApp{}
	for rows.Next() {
		var i FrappeApp
		if err := rows.Scan(
			&i.ID,
			&i.BenchID,
			&i.AppSourceID,
			&i.AppName,
			&i.CurrentCommit,
			&i.PreviousCommit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxyRoutes = `-- name: ListProxyRoutes :many
SELECT id, server_id, domain, upstream, web_app_id, ssl_enabled, ssl_expires_at, extra_snippet, config_hash, status FROM proxy_routes ORDER BY domain
`

func (q *Queries) ListProxyRoutes(ctx context.Context) ([]ProxyRoute, error) {
	rows, err := q.db.QueryContext(ctx, listProxyRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxyRoute{}
	for rows.Next() {
		var i ProxyRoute
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Domain,
			&i.Upstream,
			&i.WebAppID,
			&i.SslEnabled,
			&i.SslExpiresAt,
			&i.ExtraSnippet,
			&i.ConfigHash,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxyRoutesForServer = `-- name: ListProxyRoutesForServer :many
SELECT id, server_id, domain, upstream, web_app_id, ssl_enabled, ssl_expires_at, extra_snippet, config_hash, status FROM proxy_routes WHERE server_id = ? ORDER BY domain
`

func (q *Queries) ListProxyRoutesForServer(ctx context.Context, serverID int64) ([]ProxyRoute, error) {
	rows, err := q.db.QueryContext(ctx, listProxyRoutesForServer, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxyRoute{}
	for rows.Next() {
		var i ProxyRoute
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Domain,
			&i.Upstream,
			&i.WebAppID,
			&i.SslEnabled,
			&i.SslExpiresAt,
			&i.ExtraSnippet,
			&i.ConfigHash,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSites = `-- name: ListSites :many
SELECT id, bench_id, domain, status, apps_json, ssl_enabled, ssl_expires_at, last_backup_at, created_at FROM sites ORDER BY domain
`

func (q *Queries) ListSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.QueryContext(ctx, listSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.BenchID,
			&i.Domain,
			&i.Status,
			&i.AppsJson,
			&i.SslEnabled,
			&i.SslExpiresAt,
			&i.LastBackupAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebApps = `-- name: ListWebApps :many
SELECT id, server_id, app_source_id, name, internal_port, container_port, health_path, env_enc, current_commit, previous_commit, status FROM web_apps ORDER BY name
`

func (q *Queries) ListWebApps(ctx context.Context) ([]WebApp, error) {
	rows, err := q.db.QueryContext(ctx, listWebApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebApp{}
	for rows.Next() {
		var i WebApp
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.AppSourceID,
			&i.Name,
			&i.InternalPort,
			&i.ContainerPort,
			&i.HealthPath,
			&i.EnvEnc,
			&i.CurrentCommit,
			&i.PreviousCommit,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const routeOrSiteExistsForDomain = `-- name: RouteOrSiteExistsForDomain :one
SELECT
  (SELECT COUNT(*) FROM proxy_routes pr WHERE pr.server_id = ? AND pr.domain = ? AND pr.status != 'deleted')
  + (SELECT COUNT(*) FROM sites s WHERE s.domain = ?) AS conflicts
`

type RouteOrSiteExistsForDomainParams struct {
	ServerID int64  `json:"server_id"`
	Domain   string `json:"domain"`
	Domain_2 string `json:"domain_2"`
}

func (q *Queries) RouteOrSiteExistsForDomain(ctx context.Context, arg RouteOrSiteExistsForDomainParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, routeOrSiteExistsForDomain, arg.ServerID, arg.Domain, arg.Domain_2)
	var conflicts int64
	err := row.Scan(&conflicts)
	return conflicts, err
}

const setAppSourceAutoDeploy = `-- name: SetAppSourceAutoDeploy :exec
UPDATE app_sources SET auto_deploy = ? WHERE id = ?
`

type SetAppSourceAutoDeployParams struct {
	AutoDeploy int64 `json:"auto_deploy"`
	ID         int64 `json:"id"`
}

func (q *Queries) SetAppSourceAutoDeploy(ctx context.Context, arg SetAppSourceAutoDeployParams) error {
	_, err := q.db.ExecContext(ctx, setAppSourceAutoDeploy, arg.AutoDeploy, arg.ID)
	return err
}

const setBenchFacts = `-- name: SetBenchFacts :exec
UPDATE benches SET facts_json = ?, frappe_version = ? WHERE id = ?
`

type SetBenchFactsParams struct {
	FactsJson     string         `json:"facts_json"`
	FrappeVersion sql.NullString `json:"frappe_version"`
	ID            int64          `json:"id"`
}

func (q *Queries) SetBenchFacts(ctx context.Context, arg SetBenchFactsParams) error {
	_, err := q.db.ExecContext(ctx, setBenchFacts, arg.FactsJson, arg.FrappeVersion, arg.ID)
	return err
}

const setFrappeAppCommit = `-- name: SetFrappeAppCommit :exec
UPDATE frappe_apps SET current_commit = ? WHERE bench_id = ? AND app_name = ?
`

type SetFrappeAppCommitParams struct {
	CurrentCommit sql.NullString `json:"current_commit"`
	BenchID       int64          `json:"bench_id"`
	AppName       string         `json:"app_name"`
}

func (q *Queries) SetFrappeAppCommit(ctx context.Context, arg SetFrappeAppCommitParams) error {
	_, err := q.db.ExecContext(ctx, setFrappeAppCommit, arg.CurrentCommit, arg.BenchID, arg.AppName)
	return err
}

const setFrappeAppCommits = `-- name: SetFrappeAppCommits :exec
UPDATE frappe_apps SET previous_commit = ?, current_commit = ?
WHERE bench_id = ? AND app_name = ?
`

type SetFrappeAppCommitsParams struct {
	PreviousCommit sql.NullString `json:"previous_commit"`
	CurrentCommit  sql.NullString `json:"current_commit"`
	BenchID        int64          `json:"bench_id"`
	AppName        string         `json:"app_name"`
}

func (q *Queries) SetFrappeAppCommits(ctx context.Context, arg SetFrappeAppCommitsParams) error {
	_, err := q.db.ExecContext(ctx, setFrappeAppCommits,
		arg.PreviousCommit,
		arg.CurrentCommit,
		arg.BenchID,
		arg.AppName,
	)
	return err
}

const setProxyRouteApplied = `-- name: SetProxyRouteApplied :exec
UPDATE proxy_routes SET status = 'active', config_hash = ? WHERE id = ?
`

type SetProxyRouteAppliedParams struct {
	ConfigHash sql.NullString `json:"config_hash"`
	ID         int64          `json:"id"`
}

func (q *Queries) SetProxyRouteApplied(ctx context.Context, arg SetProxyRouteAppliedParams) error {
	_, err := q.db.ExecContext(ctx, setProxyRouteApplied, arg.ConfigHash, arg.ID)
	return err
}

const setProxyRouteStatus = `-- name: SetProxyRouteStatus :exec
UPDATE proxy_routes SET status = ? WHERE id = ?
`

type SetProxyRouteStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) SetProxyRouteStatus(ctx context.Context, arg SetProxyRouteStatusParams) error {
	_, err := q.db.ExecContext(ctx, setProxyRouteStatus, arg.Status, arg.ID)
	return err
}

const setSiteSSL = `-- name: SetSiteSSL :exec
UPDATE sites SET ssl_enabled = ?, ssl_expires_at = ? WHERE id = ?
`

type SetSiteSSLParams struct {
	SslEnabled   int64         `json:"ssl_enabled"`
	SslExpiresAt sql.NullInt64 `json:"ssl_expires_at"`
	ID           int64         `json:"id"`
}

func (q *Queries) SetSiteSSL(ctx context.Context, arg SetSiteSSLParams) error {
	_, err := q.db.ExecContext(ctx, setSiteSSL, arg.SslEnabled, arg.SslExpiresAt, arg.ID)
	return err
}

const setSiteStatus = `-- name: SetSiteStatus :exec
UPDATE sites SET status = ? WHERE id = ?
`

type SetSiteStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) SetSiteStatus(ctx context.Context, arg SetSiteStatusParams) error {
	_, err := q.db.ExecContext(ctx, setSiteStatus, arg.Status, arg.ID)
	return err
}

const setWebAppCommit = `-- name: SetWebAppCommit :exec
UPDATE web_apps SET current_commit = ?, previous_commit = ?, status = 'running' WHERE id = ?
`

type SetWebAppCommitParams struct {
	CurrentCommit  sql.NullString `json:"current_commit"`
	PreviousCommit sql.NullString `json:"previous_commit"`
	ID             int64          `json:"id"`
}

func (q *Queries) SetWebAppCommit(ctx context.Context, arg SetWebAppCommitParams) error {
	_, err := q.db.ExecContext(ctx, setWebAppCommit, arg.CurrentCommit, arg.PreviousCommit, arg.ID)
	return err
}

const setWebAppStatus = `-- name: SetWebAppStatus :exec
UPDATE web_apps SET status = ? WHERE id = ?
`

type SetWebAppStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) SetWebAppStatus(ctx context.Context, arg SetWebAppStatusParams) error {
	_, err := q.db.ExecContext(ctx, setWebAppStatus, arg.Status, arg.ID)
	return err
}

const sitesForBench = `-- name: SitesForBench :many
SELECT id, bench_id, domain, status, apps_json, ssl_enabled, ssl_expires_at, last_backup_at, created_at FROM sites WHERE bench_id = ? ORDER BY domain
`

func (q *Queries) SitesForBench(ctx context.Context, benchID int64) ([]Site, error) {
	rows, err := q.db.QueryContext(ctx, sitesForBench, benchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.BenchID,
			&i.Domain,
			&i.Status,
			&i.AppsJson,
			&i.SslEnabled,
			&i.SslExpiresAt,
			&i.LastBackupAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSiteApps = `-- name: UpdateSiteApps :exec
UPDATE sites SET apps_json = ? WHERE id = ?
`

type UpdateSiteAppsParams struct {
	AppsJson string `json:"apps_json"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateSiteApps(ctx context.Context, arg UpdateSiteAppsParams) error {
	_, err := q.db.ExecContext(ctx, updateSiteApps, arg.AppsJson, arg.ID)
	return err
}

const upsertDeployPoint = `-- name: UpsertDeployPoint :exec
INSERT INTO frappe_deploy_points (bench_id, app_name, prev_commit, backups_json)
VALUES (?, ?, ?, ?)
ON CONFLICT (bench_id, app_name)
DO UPDATE SET prev_commit = excluded.prev_commit,
              backups_json = excluded.backups_json,
              created_at = unixepoch()
`

type UpsertDeployPointParams struct {
	BenchID     int64  `json:"bench_id"`
	AppName     string `json:"app_name"`
	PrevCommit  string `json:"prev_commit"`
	BackupsJson string `json:"backups_json"`
}

func (q *Queries) UpsertDeployPoint(ctx context.Context, arg UpsertDeployPointParams) error {
	_, err := q.db.ExecContext(ctx, upsertDeployPoint,
		arg.BenchID,
		arg.AppName,
		arg.PrevCommit,
		arg.BackupsJson,
	)
	return err
}

const webAppsForSource = `-- name: WebAppsForSource :many
SELECT id, server_id, app_source_id, name, internal_port, container_port, health_path, env_enc, current_commit, previous_commit, status FROM web_apps WHERE app_source_id = ?
`

func (q *Queries) WebAppsForSource(ctx context.Context, appSourceID int64) ([]WebApp, error) {
	rows, err := q.db.QueryContext(ctx, webAppsForSource, appSourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebApp{}
	for rows.Next() {
		var i WebApp
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.AppSourceID,
			&i.Name,
			&i.InternalPort,
			&i.ContainerPort,
			&i.HealthPath,
			&i.EnvEnc,
			&i.CurrentCommit,
			&i.PreviousCommit,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
