// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package store

import (
	"context"
)

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM secrets WHERE name = ?
`

func (q *Queries) DeleteSecret(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteSecret, name)
	return err
}

const getSecret = `-- name: GetSecret :one
SELECT value_enc FROM secrets WHERE name = ? LIMIT 1
`

func (q *Queries) GetSecret(ctx context.Context, name string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getSecret, name)
	var value_enc []byte
	err := row.Scan(&value_enc)
	return value_enc, err
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT delivery_id FROM webhook_deliveries WHERE delivery_id = ? LIMIT 1
`

func (q *Queries) GetWebhookDelivery(ctx context.Context, deliveryID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getWebhookDelivery, deliveryID)
	var delivery_id string
	err := row.Scan(&delivery_id)
	return delivery_id, err
}

const purgeOldWebhookDeliveries = `-- name: PurgeOldWebhookDeliveries :exec
DELETE FROM webhook_deliveries WHERE received_at < ?
`

func (q *Queries) PurgeOldWebhookDeliveries(ctx context.Context, receivedAt int64) error {
	_, err := q.db.ExecContext(ctx, purgeOldWebhookDeliveries, receivedAt)
	return err
}

const putSecret = `-- name: PutSecret :exec
INSERT INTO secrets (name, value_enc, updated_at)
VALUES (?, ?, unixepoch())
ON CONFLICT (name) DO UPDATE SET value_enc = excluded.value_enc, updated_at = unixepoch()
`

type PutSecretParams struct {
	Name     string `json:"name"`
	ValueEnc []byte `json:"value_enc"`
}

func (q *Queries) PutSecret(ctx context.Context, arg PutSecretParams) error {
	_, err := q.db.ExecContext(ctx, putSecret, arg.Name, arg.ValueEnc)
	return err
}

const recordWebhookDelivery = `-- name: RecordWebhookDelivery :exec
INSERT INTO webhook_deliveries (delivery_id, event) VALUES (?, ?)
ON CONFLICT (delivery_id) DO NOTHING
`

type RecordWebhookDeliveryParams struct {
	DeliveryID string `json:"delivery_id"`
	Event      string `json:"event"`
}

func (q *Queries) RecordWebhookDelivery(ctx context.Context, arg RecordWebhookDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, recordWebhookDelivery, arg.DeliveryID, arg.Event)
	return err
}
