// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
)

const clearUserTOTP = `-- name: ClearUserTOTP :exec
UPDATE users SET totp_secret_enc = NULL WHERE id = ?
`

func (q *Queries) ClearUserTOTP(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearUserTOTP, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash, role)
VALUES (?, ?, ?, ?)
RETURNING id, email, name, password_hash, totp_secret_enc, role, disabled, created_at, last_login_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	Name         string `json:"name"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.TotpSecretEnc,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, totp_secret_enc, role, disabled, created_at, last_login_at FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.TotpSecretEnc,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, totp_secret_enc, role, disabled, created_at, last_login_at FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.TotpSecretEnc,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, password_hash, totp_secret_enc, role, disabled, created_at, last_login_at FROM users ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.TotpSecretEnc,
			&i.Role,
			&i.Disabled,
			&i.CreatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserDisabled = `-- name: SetUserDisabled :exec
UPDATE users SET disabled = ? WHERE id = ?
`

type SetUserDisabledParams struct {
	Disabled int64 `json:"disabled"`
	ID       int64 `json:"id"`
}

func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error {
	_, err := q.db.ExecContext(ctx, setUserDisabled, arg.Disabled, arg.ID)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = ? WHERE id = ?
`

type SetUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, setUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const setUserTOTP = `-- name: SetUserTOTP :exec
UPDATE users SET totp_secret_enc = ? WHERE id = ?
`

type SetUserTOTPParams struct {
	TotpSecretEnc []byte `json:"totp_secret_enc"`
	ID            int64  `json:"id"`
}

func (q *Queries) SetUserTOTP(ctx context.Context, arg SetUserTOTPParams) error {
	_, err := q.db.ExecContext(ctx, setUserTOTP, arg.TotpSecretEnc, arg.ID)
	return err
}

const touchUserLogin = `-- name: TouchUserLogin :exec
UPDATE users SET last_login_at = unixepoch() WHERE id = ?
`

func (q *Queries) TouchUserLogin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchUserLogin, id)
	return err
}
